global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: cart-state-server
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:28080

  - job_name: cart-display-server
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:28081
