global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: cart-state-server
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:28080

  - job_name: cart-display-server
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:28081

  - job_name: redis-exporter
    static_configs:
      - targets:
          - redis-exporter:9121

  - job_name: postgres-exporter
    static_configs:
      - targets:
          - postgres-exporter:9187
